# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Project/OSP/microblaze_based_hight_crypto_soc/vivado/vivado.srcs/sources_1/bd/mb_system/ip/mb_system_ilmb_bram_if_cntlr_2/mb_system_ilmb_bram_if_cntlr_2.xci
# IP: The module: 'mb_system_ilmb_bram_if_cntlr_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/OSP/microblaze_based_hight_crypto_soc/vivado/vivado.srcs/sources_1/bd/mb_system/ip/mb_system_ilmb_bram_if_cntlr_2/mb_system_ilmb_bram_if_cntlr_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_system_ilmb_bram_if_cntlr_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/Project/OSP/microblaze_based_hight_crypto_soc/vivado/vivado.srcs/sources_1/bd/mb_system/ip/mb_system_ilmb_bram_if_cntlr_2/mb_system_ilmb_bram_if_cntlr_2.xci
# IP: The module: 'mb_system_ilmb_bram_if_cntlr_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/OSP/microblaze_based_hight_crypto_soc/vivado/vivado.srcs/sources_1/bd/mb_system/ip/mb_system_ilmb_bram_if_cntlr_2/mb_system_ilmb_bram_if_cntlr_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_system_ilmb_bram_if_cntlr_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
