# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir d:/project/osp/microblaze_based_hight_crypto_soc/hight_top_axi4_lite/ip_repo/edit_HIGHT_TOP_AXI4_LITE_v1_0.cache/wt [current_project]
set_property parent.project_path d:/project/osp/microblaze_based_hight_crypto_soc/hight_top_axi4_lite/ip_repo/edit_HIGHT_TOP_AXI4_LITE_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths d:/Project/OSP/microblaze_based_hight_crypto_soc/HIGHT_TOP_AXI4_LITE/ip_repo/HIGHT_TOP_AXI4_LITE_1.0 [current_project]
set_property ip_output_repo d:/project/osp/microblaze_based_hight_crypto_soc/hight_top_axi4_lite/ip_repo/edit_HIGHT_TOP_AXI4_LITE_v1_0.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  d:/Project/OSP/microblaze_based_hight_crypto_soc/HIGHT_TOP_AXI4_LITE/ip_repo/HIGHT_TOP_AXI4_LITE_1.0/src/WKG.v
  d:/Project/OSP/microblaze_based_hight_crypto_soc/HIGHT_TOP_AXI4_LITE/ip_repo/HIGHT_TOP_AXI4_LITE_1.0/src/RF.v
  d:/Project/OSP/microblaze_based_hight_crypto_soc/HIGHT_TOP_AXI4_LITE/ip_repo/HIGHT_TOP_AXI4_LITE_1.0/src/WF.v
  d:/Project/OSP/microblaze_based_hight_crypto_soc/HIGHT_TOP_AXI4_LITE/ip_repo/HIGHT_TOP_AXI4_LITE_1.0/src/SKG.v
  d:/Project/OSP/microblaze_based_hight_crypto_soc/HIGHT_TOP_AXI4_LITE/ip_repo/HIGHT_TOP_AXI4_LITE_1.0/src/CRYPTO_PATH.v
  d:/Project/OSP/microblaze_based_hight_crypto_soc/HIGHT_TOP_AXI4_LITE/ip_repo/HIGHT_TOP_AXI4_LITE_1.0/src/KEY_SCHED.v
  d:/Project/OSP/microblaze_based_hight_crypto_soc/HIGHT_TOP_AXI4_LITE/ip_repo/HIGHT_TOP_AXI4_LITE_1.0/src/CONTROL.v
  d:/Project/OSP/microblaze_based_hight_crypto_soc/HIGHT_TOP_AXI4_LITE/ip_repo/HIGHT_TOP_AXI4_LITE_1.0/src/HIGHT_CORE_TOP.v
  d:/Project/OSP/microblaze_based_hight_crypto_soc/HIGHT_TOP_AXI4_LITE/ip_repo/HIGHT_TOP_AXI4_LITE_1.0/src/HIGHT_CORE_TOP_WRAPPER.v
  d:/Project/OSP/microblaze_based_hight_crypto_soc/HIGHT_TOP_AXI4_LITE/ip_repo/HIGHT_TOP_AXI4_LITE_1.0/hdl/HIGHT_TOP_AXI4_LITE_v1_0_S_AXI.v
  d:/Project/OSP/microblaze_based_hight_crypto_soc/HIGHT_TOP_AXI4_LITE/ip_repo/HIGHT_TOP_AXI4_LITE_1.0/hdl/HIGHT_TOP_AXI4_LITE_v1_0.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top HIGHT_TOP_AXI4_LITE_v1_0 -part xc7z010clg400-1


write_checkpoint -force -noxdef HIGHT_TOP_AXI4_LITE_v1_0.dcp

catch { report_utilization -file HIGHT_TOP_AXI4_LITE_v1_0_utilization_synth.rpt -pb HIGHT_TOP_AXI4_LITE_v1_0_utilization_synth.pb }
